_merge: deep

header:
  expand: none

logo:
  header: '/assets/images/logo.png'
  footer: '/assets/images/logo.png'

# Image
hero:
  cover:
    desktop: 1600x1000
products:
  thumbnail:
    desktop: 370x320
    mobile: 314x270
blocks:
  gallery:
    image:
      ratio: 1.5

# Admin
admin:
  cms: sveltiacms
  name: github
  repo: sebousan/hugolify-sveltia-test
  netlify:
    identity: false

  i18n:
    default_locale: fr
    # locales: "[fr,en]"

  collections:
    indexes:
      enable: false
    pages:
      nested:
        depth: 1
